services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-app:${IMAGE_TAG:-latest}
    container_name: frontend
    ports:
      - "4200:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-check-certificate --spider -q https://localhost:443 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s