spring.application.name=user-service

server.port=8081
spring.data.mongodb.uri=mongodb://admin:123456@localhost:27017/user-db?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.stream.bindings.userProducer-out-0.destination=userTopic
spring.cloud.stream.bindings.userProducer-out-0.contentType=application/json

# 2. Déclaration explicite des 2 consommateurs
spring.cloud.function.definition=userConsumer;userConsumerAvatar

# Consumer 1 : authTopic -> userConsumer
spring.cloud.stream.bindings.userConsumer-in-0.destination=authTopic
spring.cloud.stream.bindings.userConsumer-in-0.group=user-service-group
spring.cloud.stream.bindings.userConsumer-in-0.contentType=application/json

# Consumer 2 : mediaTopic -> userConsumerAvatar
spring.cloud.stream.bindings.userConsumerAvatar-in-0.destination=mediaTopic
spring.cloud.stream.bindings.userConsumerAvatar-in-0.group=user-service-group
spring.cloud.stream.bindings.userConsumerAvatar-in-0.contentType=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092