spring.application.name=media-service

server.port=8083
spring.cloud.discovery.enabled=true
management.endpoints.web.exposure.include=*
spring.data.mongodb.uri=mongodb://mongodb:27017/media_db

# spring.cloud.function.definition=productConsumer
# spring.cloud.stream.bindings.productConsumer-in-0.destination=productTopic
# spring.cloud.stream.bindings.productConsumer-in-0.group=media-service-group
# spring.cloud.stream.bindings.productConsumer-in-0.contentType=application/json
# spring.cloud.stream.kafka.binder.brokers=localhost:9092
