spring.application.name=product-service

server.port=8082
spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/product-db?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.stream.bindings.productProducer-out-0.destination=productTopic
spring.cloud.stream.bindings.productProducer-out-0.contentType=application/json


spring.cloud.function.definition=productConsumer
spring.cloud.stream.bindings.productConsumer-in-0.destination=mediaTopic
spring.cloud.stream.bindings.productConsumer-in-0.group=media-service-group
spring.cloud.stream.bindings.productConsumer-in-0.contentType=application/json

# spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.brokers=kafka:9092
