spring.application.name=product-service

server.port=8082
spring.datasource.url=jdbc:h2:mem:product-db
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.data.rest.base-path=/api
management.endpoints.web.exposure.include=*

# spring.cloud.function.definition=userConsumer
# spring.cloud.stream.bindings.userConsumer-in-0.destination=userTopic
# spring.cloud.stream.bindings.userConsumer-in-0.group=product-service-group
# spring.cloud.stream.bindings.userConsumer-in-0.contentType=application/json

# spring.cloud.stream.bindings.productProducer-out-0.destination=productTopic
# spring.cloud.stream.bindings.productProducer-out-0.contentType=application/json

# spring.cloud.stream.kafka.binder.brokers=localhost:9092
