spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-auth
              uri: lb://SECURITY-SERVICE
              predicates:
                Path=/api/auth/**
            - id: r1
              uri: lb://USER-SERVICE
              predicates:
                Path=/api/users/**
            - id: r2
              uri: lb://PRODUCT-SERVICE
              predicates:
                Path=/api/products/**
            - id: r3
              uri: lb://MEDIA-SERVICE
              predicates:
                Path=/api/medias/**