services:

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    command: --storage-driver overlay2
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - "2376:2376"
      - "8888:8888"
      - "8761:8761"
    volumes:
      - jenkins-docker-certs:/certs/client
    restart: always

  jenkins-blueocean:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      network: host
    image: myjenkins-blueocean:2.568.3-1
    container_name: jenkins-blueocean
    network_mode: host
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - jenkins-docker
    restart: on-failure

volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs